// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://szqvtueegfqsekcpujgi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN6cXZ0dWVlZ2Zxc2VrY3B1amdpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzMjAxNTEsImV4cCI6MjA2Nzg5NjE1MX0.rdzLF8seSZIuTIgOtPBG9sivSfbNpdgSlB3-KxMvzqg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});